FROM debian:bookworm

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        build-essential \
        git \
        gnupg \
        libssl-dev \
        libffi-dev \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev \
        pipx \
        sudo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash uniclogs

RUN python3 -m venv /opt/venv
RUN chown -R uniclogs:uniclogs /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /workspace
USER uniclogs
