[build-system]
requires = ["setuptools>=75", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "uniclogs-stationd"
description = "A power management Daemon for Uniclogs."
requires-python = ">=3.11"
license = {text = "GPL-3.0"}
dynamic = ["version"]
readme = "README.md"
authors = [
    { name = "Steven Borrego" }
]

dependencies = []

[project.optional-dependencies]
dev = [
    "flake8",
    "sphinx",
    "pytest>=8.4.0",
    "pytest-cov>=6.2.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
norecursedirs = [".git", ".venv", "__pycache__", "examples", "gpio", "htmlcov"]
addopts = [
    "--cov=.",
    "--cov-report=term-missing",
    "--cov-report=html:htmlcov"
]

[tool.coverage.run]
source = ["."]
omit = [
    ".venv/*", "__pycache__/*", "examples/*", "gpio/*", "htmlcov/*", "tests/*"
]

[tool.flake8]
max-line-length = 99
extend-ignore = ["E402"]
per-file-ignore = "__init__.py: F401"
exclude = [
    ".git", ".venv", "__pycache__", "build", "examples", "gpio", "htmlcov"
]
