name: Upload Python Package

on:
  release:
    types: [ "published" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Mint an API token
      id: mint-token
      run: |
        resp=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=pypi")
        oidc_token=$(jq -r '.value' <<< "${resp}")

        resp=$(curl -X POST https://pypi.org/_/oidc/mint-token -d "{\"token\": \"${oidc_token}\"}")
        api_token=$(jq -r '.token' <<< "${resp}")

        echo "::add-mask::${api_token}"

        echo "api-token=${api_token}" >> "${GITHUB_OUTPUT}"

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ steps.mint-token.outputs.api-token }}
