name: Tests and lints for StationD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    # TODO: Remove this when GPIO submodule is replaced with gpiod
    - name: Initialize GPIO submodule
      run: |
        git submodule update --init
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Lint with Ruff
      run: |
        ruff check
    - name: Format with Ruff
      run: |
        ruff format --check
    # TODO: Remove --exclude flag when GPIO submodule is replaced with gpiod
    - name: Typecheck with mypy
      run: |
        mypy src/stationd --exclude="src/stationd/gpio"
    - name: Test with pytest
      run: |
        pytest
